16.10.2021 08:50:47 INFO  [main] orage.db.DatabaseConfiguration - [user:] Database connection to h2 using jdbc:h2:mem:test;TRACE_LEVEL_FILE=4
16.10.2021 08:50:47 INFO  [main] storage.db.DatabaseInitializer - [user:] Creating database populator using script 'scripts/db/h2.create.ddl.sql'
16.10.2021 08:50:47 INFO  [main] storage.db.DatabaseInitializer - [user:] Database created.
16.10.2021 08:50:47 INFO  [main] storage.db.DatabaseInitializer - [user:] Creating database populator using script 'scripts/db/fails.create.ddl.sql'
16.10.2021 08:50:47 ERROR [main] h2database                     - [user:] jdbc[3] exception
org.h2.jdbc.JdbcSQLException: Table "FOO" already exists; SQL statement:
create table foo [42101-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.message.DbException.get(DbException.java:179) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.message.DbException.get(DbException.java:155) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:115) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.command.CommandContainer.update(CommandContainer.java:78) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.command.Command.executeUpdate(Command.java:253) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184) ~[h2-1.4.190.jar:1.4.190]
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158) ~[h2-1.4.190.jar:1.4.190]
	at com.zaxxer.hikari.proxy.StatementProxy.execute(StatementProxy.java:83) [HikariCP-java6-2.3.12.jar:na]
	at com.zaxxer.hikari.proxy.HikariStatementProxy.execute(HikariStatementProxy.java) [HikariCP-java6-2.3.12.jar:na]
	at org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript(ScriptUtils.java:472) [spring-jdbc-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.jdbc.datasource.init.ResourceDatabasePopulator.populate(ResourceDatabasePopulator.java:229) [spring-jdbc-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.jdbc.datasource.init.DatabasePopulatorUtils.execute(DatabasePopulatorUtils.java:48) [spring-jdbc-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at com.nitorcreations.nflow.engine.internal.storage.db.DatabaseInitializer.populate(DatabaseInitializer.java:30) [classes/:na]
	at com.nitorcreations.nflow.engine.internal.storage.db.DatabaseInitializer.<init>(DatabaseInitializer.java:25) [classes/:na]
	at com.nitorcreations.nflow.engine.internal.storage.db.DatabaseInitializerTest.databaseCreationDoesNotThrowExceptionWhenDatabaseIsAlreadyCreated(DatabaseInitializerTest.java:39) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_292]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75) [spring-test-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86) [spring-test-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239) [junit-4.12.jar:4.12]
	at org.junit.rules.RunRules.evaluate(RunRules.java:20) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84) [spring-test-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:254) [spring-test-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:89) [spring-test-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61) [spring-test-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70) [spring-test-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:193) [spring-test-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:344) [surefire-junit4-2.19.jar:2.19]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:269) [surefire-junit4-2.19.jar:2.19]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:240) [surefire-junit4-2.19.jar:2.19]
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:184) [surefire-junit4-2.19.jar:2.19]
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286) [surefire-booter-2.19.jar:2.19]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240) [surefire-booter-2.19.jar:2.19]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121) [surefire-booter-2.19.jar:2.19]
16.10.2021 08:50:47 WARN  [main] storage.db.DatabaseInitializer - [user:] Failed to create the database, possibly already created: Failed to execute SQL script statement #2 of class path resource [scripts/db/fails.create.ddl.sql]: create table foo; nested exception is org.h2.jdbc.JdbcSQLException: Table "FOO" already exists; SQL statement:
create table foo [42101-190]
